# -----
# Site
# -----

title: Ssup2 Blog
url: https://ssup2.github.io
baseurl:
google_analytics_key: UA-77446431-3
show_full_navigation: true

# -----
# Build
# -----

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
    categories:
      output: true

    docs:
      title: Documentation
      permalink: /:path/
      output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

# -----
# seo-tag
# -----

title: Ssup2 Blog
description: Ssup2의 개인 블로그입니다.
url: https://ssup2.github.io
logo: /siteicon.png
author: Ssup2
social:
  name: Ssup2
  links:
    - https://ssup2.github.io
